version: "3.8"

services:
  biko-api:
    build:
      context: .
      args:
        PORT: ${PORT}
        DATABASE_URL: ${DATABASE_URL}
        JWT_SECRET: ${JWT_SECRET}
    container_name: biko-api
    restart: always
    networks:
      - proxy
    expose:
      - "${PORT}"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}

networks:
  proxy:
    external: true
