version: "3.8"

services:
  biko-api:
    build: .
    container_name: biko-api
    restart: always
    networks:
      - proxy
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    expose:
      - "${PORT}"

networks:
  proxy:
    external: true
