services:
  biko-api:
    build: .
    container_name: biko-api
    restart: always
    networks:
      - proxy
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${PORT}:${PORT}"

networks:
  proxy:
    external: true
