INSERT INTO service (id, name, createdAt, updatedAt)
VALUES
  (gen_random_uuid(), 'Pintor', NOW(), NOW()),
  (gen_random_uuid(), 'Eletricista', NOW(), NOW()),
  (gen_random_uuid(), 'Encanador', NOW(), NOW()),
  (gen_random_uuid(), 'Pedreiro', NOW(), NOW()),
  (gen_random_uuid(), 'Carpinteiro', NOW(), NOW()),
  (gen_random_uuid(), 'Marceneiro', NOW(), NOW()),
  (gen_random_uuid(), 'Gesseiro', NOW(), NOW()),
  (gen_random_uuid(), 'Serralheiro', NOW(), NOW()),
  (gen_random_uuid(), 'Jardineiro', NOW(), NOW()),
  (gen_random_uuid(), 'Paisagista', NOW(), NOW()),
  (gen_random_uuid(), 'Montador de móveis', NOW(), NOW()),
  (gen_random_uuid(), 'Reformas em geral', NOW(), NOW()),
  (gen_random_uuid(), 'Diarista', NOW(), NOW()),
  (gen_random_uuid(), 'Faxineira', NOW(), NOW()),
  (gen_random_uuid(), 'Passadeira', NOW(), NOW()),
  (gen_random_uuid(), 'Técnico de informática', NOW(), NOW()),
  (gen_random_uuid(), 'Técnico de celular', NOW(), NOW()),
  (gen_random_uuid(), 'Instalador de ar-condicionado', NOW(), NOW()),
  (gen_random_uuid(), 'Manutenção de ar-condicionado', NOW(), NOW()),
  (gen_random_uuid(), 'Instalador de câmeras de segurança', NOW(), NOW()),
  (gen_random_uuid(), 'Motorista particular', NOW(), NOW()),
  (gen_random_uuid(), 'Chaveiro', NOW(), NOW()),
  (gen_random_uuid(), 'Alarme residencial', NOW(), NOW()),
  (gen_random_uuid(), 'Babá', NOW(), NOW()),
  (gen_random_uuid(), 'Cuidador de idosos', NOW(), NOW()),
  (gen_random_uuid(), 'Vidraceiro', NOW(), NOW()),
  (gen_random_uuid(), 'Tapeceiro', NOW(), NOW()),
  (gen_random_uuid(), 'Dedetizador', NOW(), NOW()),
  (gen_random_uuid(), 'Segurança particular', NOW(), NOW()),
  (gen_random_uuid(), 'Personal trainer', NOW(), NOW()),
  (gen_random_uuid(), 'Professor particular', NOW(), NOW()),
  (gen_random_uuid(), 'Consultor financeiro', NOW(), NOW()),
  (gen_random_uuid(), 'Contador', NOW(), NOW()),
  (gen_random_uuid(), 'Advogado', NOW(), NOW()),
  (gen_random_uuid(), 'Designer gráfico', NOW(), NOW()),
  (gen_random_uuid(), 'Fotógrafo', NOW(), NOW()),
  (gen_random_uuid(), 'Cinegrafista', NOW(), NOW()),
  (gen_random_uuid(), 'Editor de vídeo', NOW(), NOW()),
  (gen_random_uuid(), 'Social media', NOW(), NOW()),
  (gen_random_uuid(), 'Marketing digital', NOW(), NOW()),
  (gen_random_uuid(), 'Desenvolvedor', NOW(), NOW()),
  (gen_random_uuid(), 'Mecânico', NOW(), NOW()),
  (gen_random_uuid(), 'Funileiro', NOW(), NOW()),
  (gen_random_uuid(), 'Borracheiro', NOW(), NOW()),
  (gen_random_uuid(), 'Lavagem de carros', NOW(), NOW()),
  (gen_random_uuid(), 'Motoboy', NOW(), NOW()),
  (gen_random_uuid(), 'Delivery', NOW(), NOW()),
  (gen_random_uuid(), 'Cabeleireiro', NOW(), NOW()),
  (gen_random_uuid(), 'Barbeiro', NOW(), NOW()),
  (gen_random_uuid(), 'Manicure', NOW(), NOW()),
  (gen_random_uuid(), 'Pedicure', NOW(), NOW()),
  (gen_random_uuid(), 'Esteticista', NOW(), NOW()),
  (gen_random_uuid(), 'Massagista', NOW(), NOW()),
  (gen_random_uuid(), 'Tatuador', NOW(), NOW()),
  (gen_random_uuid(), 'Piercer', NOW(), NOW()),
  (gen_random_uuid(), 'Costureira', NOW(), NOW()),
  (gen_random_uuid(), 'Sapateiro', NOW(), NOW()),
  (gen_random_uuid(), 'Barman', NOW(), NOW()),
  (gen_random_uuid(), 'Garçom', NOW(), NOW()),
  (gen_random_uuid(), 'Cozinheiro', NOW(), NOW()),
  (gen_random_uuid(), 'Confeiteiro', NOW(), NOW()),
  (gen_random_uuid(), 'Buffet para eventos', NOW(), NOW()),
  (gen_random_uuid(), 'DJ', NOW(), NOW()),
  (gen_random_uuid(), 'Músico', NOW(), NOW()),
  (gen_random_uuid(), 'Decorador de festas', NOW(), NOW()),
  (gen_random_uuid(), 'Organizador de eventos', NOW(), NOW()),
  (gen_random_uuid(), 'Guia turístico', NOW(), NOW()),
  (gen_random_uuid(), 'Tradutor', NOW(), NOW()),
  (gen_random_uuid(), 'Reforço escolar', NOW(), NOW()),
  (gen_random_uuid(), 'Aulas de idiomas', NOW(), NOW()),
  (gen_random_uuid(), 'Aulas de música', NOW(), NOW()),
  (gen_random_uuid(), 'Aulas de dança', NOW(), NOW()),
  (gen_random_uuid(), 'Aulas de artes', NOW(), NOW()),
  (gen_random_uuid(), 'Veterinário', NOW(), NOW()),
  (gen_random_uuid(), 'Adestrador de cães', NOW(), NOW()),
  (gen_random_uuid(), 'Pet sitter', NOW(), NOW()),
  (gen_random_uuid(), 'Passeador de cães', NOW(), NOW()),
  (gen_random_uuid(), 'Consultoria de energia solar', NOW(), NOW()),
  (gen_random_uuid(), 'Mudanças e fretes', NOW(), NOW());
